apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: source-api-conformance-template
spec:
  revisionPath: ".status.outputs.revision"
  template:
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: "$(workload.metadata.name)$-api-compliance-test"
    spec:
      inputs:
        source-revision: "$(sources.source.revision)$"
        source-url: "$(sources.source.url)$"
      runTemplateRef:
        kind: ClusterRunTemplate
        name: run-api-conformance-template
      serviceAccountName: "$(workload.spec.serviceAccountName)$"
  urlPath: ".status.outputs.url"

